name: Django Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install Python and dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django
        pip install pytest
        pip install flake8

    # Set DJANGO_SETTINGS_MODULE
    - name: Set DJANGO_SETTINGS_MODULE
      run: export DJANGO_SETTINGS_MODULE=epsic_library.settings  # Adjust path if necessary

    # Initialize Django settings
    - name: Initialize Django settings
      run: python -c "import django; from django.conf import settings; settings.configure()" 

    # Initialize Django
    - name: Initialize Django
      run: python -c "import django; django.setup()"

    # Run Tests
    - name: Run Tests
      run: |
        python -m pytest -v
