name: Django web app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install Python and dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Copy pytest.ini file
    - name: Copy pytest.ini
      run: cp path/to/pytest.ini .

    # Run Tests
    - name: Run Tests
      run: python -m pytest -v
